fullnameOverride: hydrosat-external-secrets

installCRDs: true

serviceAccount:
  create: true
  name: hydrosat-external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::564268553986:role/hydrosat-dev-external-secrets-irsa

serviceMonitor:
  enabled: true
  namespace: monitoring

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
