apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: hydrosat-aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: REPLACE_WITH_AWS_REGION
      auth:
        jwt:
          serviceAccountRef:
            name: hydrosat-external-secrets
            namespace: external-secrets
