apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydrosat-dagster-db
  namespace: dagster
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: hydrosat-aws-secretsmanager
  target:
    name: hydrosat-dagster-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        url: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .dbname }}"
  data:
    - secretKey: username
      remoteRef:
        key: REPLACE_WITH_RDS_MASTER_SECRET_ARN
        property: username
    - secretKey: password
      remoteRef:
        key: REPLACE_WITH_RDS_MASTER_SECRET_ARN
        property: password
    - secretKey: host
      remoteRef:
        key: REPLACE_WITH_RDS_MASTER_SECRET_ARN
        property: host
    - secretKey: port
      remoteRef:
        key: REPLACE_WITH_RDS_MASTER_SECRET_ARN
        property: port
    - secretKey: dbname
      remoteRef:
        key: REPLACE_WITH_RDS_MASTER_SECRET_ARN
        property: dbname
