apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydrosat-grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: hydrosat-aws-secretsmanager
  target:
    name: hydrosat-grafana-admin
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-user: "{{ .adminUser }}"
        admin-password: "{{ .adminPassword }}"
  data:
    - secretKey: adminUser
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-iCjakm
        property: adminUser
    - secretKey: adminPassword
      remoteRef:
        key: arn:aws:secretsmanager:us-east-1:564268553986:secret:hydrosat/dev/grafana-iCjakm
        property: adminPassword
