image:
  repository: REPLACE_WITH_CONTAINER_IMAGE_REPOSITORY
  tag: latest

alerting:
  alertmanagerUrl: http://hydrosat-monitoring-alertmanager.monitoring.svc.cluster.local:9093/api/v2/alerts

database:
  host: REPLACE_WITH_RDS_ADDRESS
  port: 5432
  name: dagster
  username: dagster
  secretName: hydrosat-dagster-db
  createSecret: false
