{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hydrosat-dagster.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "hydrosat-dagster.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
